name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: ${{ matrix.downgrade && 'Downgrade / ' || '' }}Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.3'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        downgrade:
          - false
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x64
            downgrade: true
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: cjdoris/julia-downgrade-compat-action@v1
        with:
          skip: Artifacts, Test
        if: ${{ matrix.downgrade }}
        name: Downgrade dependencies to oldest supported versions
      - uses: julia-actions/julia-buildpkg@v1
      - name: Clone posteriordb
        uses: actions/checkout@v4
        with:
          repository: stan-dev/posteriordb
          path: 'posteriordb'
        if: matrix.version == '1.0'
      - name: Set POSTERIOR_DB_PATH environmental variable
        run: |
          echo "POSTERIOR_DB_PATH=$GITHUB_WORKSPACE/posteriordb/posterior_database" >> $GITHUB_ENV
        if: matrix.version == '1.0'
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using PosteriorDB
            DocMeta.setdocmeta!(PosteriorDB, :DocTestSetup, :(using PosteriorDB); recursive=true)
            doctest(PosteriorDB)'
